on: push
name: docker
jobs:
  deploy:
    name: syslog
    runs-on: ubuntu-latest
    steps:
    # https://github.com/marketplace/actions/checkout
    - uses: actions/checkout@v2
    - name: build and push to docker
      # https://github.com/marketplace/actions/build-and-push-docker-images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}, alpine
